export const COUNT_INCREMENT = 'COUNT_INCREMENT';
export const COUNT_DECREMENT = 'COUNT_DECREMENT';
export const ISLOADING_CHANGE = 'ISLOADING_CHANGE';
export const CATEGORY_NUMBER_CHANGE = 'CATEGORY_NUMBER_CHANGE';
export const CATEGORY_CATEGORIES_ADD = 'CATEGORY_CATEGORIES_ADD';
export const CATEGORY_CATEGORIES_SET = 'CATEGORY_CATEGORIES_SET';
export const CATEGORY_CATEGORIES_CHANGE = 'CATEGORY_CATEGORIES_CHANGE';
export const CATEGORY_CATEGORIES_DELETE = 'CATEGORY_CATEGORIES_DELETE';
